import type { Metadata } from "next";
import { Alice } from "next/font/google";
import { Header } from "app/Components/Shared/Header";
import { Footer } from "app/Components/Shared/Footer";
import "../Sass/globals.sass";

const alice = Alice({
  weight: "400",
  subsets: ["latin-ext"],
});


export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alice.className} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
