export const env = {
	SHOPIFY_TOKEN: process.env.SHOPIFY_TOKEN || "",
	SHOPIFY_HOSTNAME: process.env.SHOPIFY_HOSTNAME || "",
	CACHE_TOKEN: "7DEE4BF36CF494B53E2D125884FBD",
	SHOPIFY_GRAPHQL_ENDPOINT: process.env.SHOPIFY_GRAPHQL_ENDPOINT as string,
	SHOPIFY_STOREFRONT_TOKEN: process.env.SHOPIFY_STOREFRONT_TOKEN as string,
 }